version: "3.9"
services:
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/netology_diploma_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 49918003
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  database:
    image: mysql/mysql-server:latest
    container_name: 'Netology-db'
    volumes:
      - /mysql_data:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 49918003
      MYSQL_ROOT_PASSWORD: 49918003
      MYSQL_DATABASE: netology_diploma_db
    ports:
      - "4000:4000"